// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBksY1uieB-aWu0NqxV8I0MYNJWZOirmRk',
    appId: '1:907418516507:web:8cc208fa9bd7b8c0b9ccbe',
    messagingSenderId: '907418516507',
    projectId: 'fooddeliveryapp-f813f',
    authDomain: 'fooddeliveryapp-f813f.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-f813f.appspot.com',
    measurementId: 'G-BRMWF68YXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJwTOs1xSmKfHCZ8vh8npMFR16iFaAlE',
    appId: '1:907418516507:android:260cba094621736bb9ccbe',
    messagingSenderId: '907418516507',
    projectId: 'fooddeliveryapp-f813f',
    storageBucket: 'fooddeliveryapp-f813f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMhJDUiXIuQn5WZ-bUYKZD4HukeC9yehc',
    appId: '1:907418516507:ios:d4447be47012ce35b9ccbe',
    messagingSenderId: '907418516507',
    projectId: 'fooddeliveryapp-f813f',
    storageBucket: 'fooddeliveryapp-f813f.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMhJDUiXIuQn5WZ-bUYKZD4HukeC9yehc',
    appId: '1:907418516507:ios:d4447be47012ce35b9ccbe',
    messagingSenderId: '907418516507',
    projectId: 'fooddeliveryapp-f813f',
    storageBucket: 'fooddeliveryapp-f813f.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBksY1uieB-aWu0NqxV8I0MYNJWZOirmRk',
    appId: '1:907418516507:web:446b915593f34836b9ccbe',
    messagingSenderId: '907418516507',
    projectId: 'fooddeliveryapp-f813f',
    authDomain: 'fooddeliveryapp-f813f.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-f813f.appspot.com',
    measurementId: 'G-PRGMBXJYKW',
  );
}
